require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HighScoresController do

  # This should return the minimal set of attributes required to create a valid
  # HighScore. As you add validations to HighScore, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all high_scores as @high_scores" do
      high_score = HighScore.create! valid_attributes
      get :index
      assigns(:high_scores).should eq([high_score])
    end
  end

  describe "GET show" do
    it "assigns the requested high_score as @high_score" do
      high_score = HighScore.create! valid_attributes
      get :show, :id => high_score.id.to_s
      assigns(:high_score).should eq(high_score)
    end
  end

  describe "GET new" do
    it "assigns a new high_score as @high_score" do
      get :new
      assigns(:high_score).should be_a_new(HighScore)
    end
  end

  describe "GET edit" do
    it "assigns the requested high_score as @high_score" do
      high_score = HighScore.create! valid_attributes
      get :edit, :id => high_score.id.to_s
      assigns(:high_score).should eq(high_score)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HighScore" do
        expect {
          post :create, :high_score => valid_attributes
        }.to change(HighScore, :count).by(1)
      end

      it "assigns a newly created high_score as @high_score" do
        post :create, :high_score => valid_attributes
        assigns(:high_score).should be_a(HighScore)
        assigns(:high_score).should be_persisted
      end

      it "redirects to the created high_score" do
        post :create, :high_score => valid_attributes
        response.should redirect_to(HighScore.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved high_score as @high_score" do
        # Trigger the behavior that occurs when invalid params are submitted
        HighScore.any_instance.stub(:save).and_return(false)
        post :create, :high_score => {}
        assigns(:high_score).should be_a_new(HighScore)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HighScore.any_instance.stub(:save).and_return(false)
        post :create, :high_score => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested high_score" do
        high_score = HighScore.create! valid_attributes
        # Assuming there are no other high_scores in the database, this
        # specifies that the HighScore created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HighScore.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => high_score.id, :high_score => {'these' => 'params'}
      end

      it "assigns the requested high_score as @high_score" do
        high_score = HighScore.create! valid_attributes
        put :update, :id => high_score.id, :high_score => valid_attributes
        assigns(:high_score).should eq(high_score)
      end

      it "redirects to the high_score" do
        high_score = HighScore.create! valid_attributes
        put :update, :id => high_score.id, :high_score => valid_attributes
        response.should redirect_to(high_score)
      end
    end

    describe "with invalid params" do
      it "assigns the high_score as @high_score" do
        high_score = HighScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HighScore.any_instance.stub(:save).and_return(false)
        put :update, :id => high_score.id.to_s, :high_score => {}
        assigns(:high_score).should eq(high_score)
      end

      it "re-renders the 'edit' template" do
        high_score = HighScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HighScore.any_instance.stub(:save).and_return(false)
        put :update, :id => high_score.id.to_s, :high_score => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested high_score" do
      high_score = HighScore.create! valid_attributes
      expect {
        delete :destroy, :id => high_score.id.to_s
      }.to change(HighScore, :count).by(-1)
    end

    it "redirects to the high_scores list" do
      high_score = HighScore.create! valid_attributes
      delete :destroy, :id => high_score.id.to_s
      response.should redirect_to(high_scores_url)
    end
  end

end
